export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"

export const SOCIAL_LOGIN = "SOCIAL_LOGIN"

export const SET_SESSION_TOKEN = 'SET_SESSION_TOKEN';
export const REMOVE_SESSION_TOKEN = 'REMOVE_SESSION_TOKEN';

export const HANDLE_SESSION = 'HANDLE_SESSION';
export const SET_COOKIE = 'SET_COOKIE';
export const GET_COOKIE = 'GET_COOKIE';
export const REMOVE_COOKIE = 'REMOVE_COOKIE';
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const BROWSER_GET = 'BROWSER_GET';
export const BROWSER_SET = 'BROWSER_SET';
export const GET_REQUEST = 'GET_REQUEST';
export const POST_REQUEST = 'POST_REQUEST';
export const GET_DATA_FAILURE = 'GET_FREE_DATA_FAILURE'
export const POST_DATA_FAILURE = 'POST_DATA_FAILURE'
export const AUTHORIZATION = 'AUTHORIZATION';
export const AUTHORIZATION_FAILURE ='AUTHORIZATION_FAILURE  '